import {
  Flex,
  Heading,
  Image,
  Link,
  ListItem,
  UnorderedList,
} from "@chakra-ui/react";

const Footer = () => {
  return (
    <Flex bg={"primary-1"} justifyContent={"center"} width={"100%"}>
      <Flex
        paddingY={"4em"}
        maxWidth={"844px"}
        width={"100%"}
        columnGap={"2em"}
        justifyContent={"space-between"}
      >
        <Image
          src="/images/Asset 9@4x.png"
          alt="footer-logo"
          w={"120px"}
          h={"220px"}
          alignSelf={'center'}
        />
        <Flex
          flexDirection={"column"}
          rowGap={"2em"}
          paddingY={"0.6em"}
        >
          <Heading
            as={"h3"}
            color={"secondary-2"}
            fontSize={"1.2em"}
            fontWeight={"bold"}
          >
            Navigation
          </Heading>
          <UnorderedList
            as="nav"
            margin={0}
            listStyleType={"none"}
            display={"flex"}
            flexDirection={"column"}
            rowGap={"0.2em"}
          >
            <ListItem>
              <Link
                color={"highlight-1"}
                fontSize={"1.2em"}
                fontWeight={"medium"}
              >
                Home
              </Link>
            </ListItem>
            <ListItem>
              <Link
                color={"highlight-1"}
                fontSize={"1.2em"}
                fontWeight={"medium"}
              >
                About
              </Link>
            </ListItem>
            <ListItem>
              <Link
                color={"highlight-1"}
                fontSize={"1.2em"}
                fontWeight={"medium"}
              >
                Menu
              </Link>
            </ListItem>
            <ListItem>
              <Link
                color={"highlight-1"}
                fontSize={"1.2em"}
                fontWeight={"medium"}
              >
                Reservations
              </Link>
            </ListItem>
            <ListItem>
              <Link
                color={"highlight-1"}
                fontSize={"1.2em"}
                fontWeight={"medium"}
              >
                Order online
              </Link>
            </ListItem>
            <ListItem>
              <Link
                color={"highlight-1"}
                fontSize={"1.2em"}
                fontWeight={"medium"}
              >
                Login
              </Link>
            </ListItem>
          </UnorderedList>
        </Flex>

        <Flex
          flexDirection={"column"}
          rowGap={"2em"}
          paddingY={"0.6em"}
        >
          <Heading
            as={"h3"}
            color={"secondary-2"}
            fontSize={"1.2em"}
            fontWeight={"bold"}
          >
            Contact
          </Heading>
          <UnorderedList
            margin={0}
            listStyleType={"none"}
            display={"flex"}
            flexDirection={"column"}
            rowGap={"0.2em"}
          >
            <ListItem>
              <Link
                color={"highlight-1"}
                fontSize={"1.2em"}
                fontWeight={"medium"}
              >
                Address
              </Link>
            </ListItem>
            <ListItem>
              <Link
                color={"highlight-1"}
                fontSize={"1.2em"}
                fontWeight={"medium"}
              >
                Phone number
              </Link>
            </ListItem>
            <ListItem>
              <Link
                color={"highlight-1"}
                fontSize={"1.2em"}
                fontWeight={"medium"}
              >
                Email
              </Link>
            </ListItem>
          </UnorderedList>
        </Flex>

        <Flex
          flexDirection={"column"}
          rowGap={"2em"}
          paddingY={"0.6em"}
        >
          <Heading
            as={"h3"}
            color={"secondary-2"}
            fontSize={"1.2em"}
            fontWeight={"bold"}
          >
            Social media links
          </Heading>
          <UnorderedList
            margin={0}
            listStyleType={"none"}
            display={"flex"}
            flexDirection={"column"}
            rowGap={"0.2em"}
          >
            <ListItem>
              <Link
                color={"highlight-1"}
                fontSize={"1.2em"}
                fontWeight={"medium"}
              >
                Facebook
              </Link>
            </ListItem>
            <ListItem>
              <Link
                color={"highlight-1"}
                fontSize={"1.2em"}
                fontWeight={"medium"}
              >
                Instagram
              </Link>
            </ListItem>
            <ListItem>
              <Link
                color={"highlight-1"}
                fontSize={"1.2em"}
                fontWeight={"medium"}
              >
                Whatsapp
              </Link>
            </ListItem>
          </UnorderedList>
        </Flex>
      </Flex>
    </Flex>
  );
};

export default Footer;
